# Generated by Django 2.2.2 on 2019-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phoneno', models.IntegerField()),
                ('c_subject', models.CharField(max_length=50)),
                ('c_massage', models.TextField()),
            ],
        ),
        migrations.AlterModelTable(
            name='registation',
            table='registation',
        ),
    ]
