# Generated by Django 2.2.2 on 2019-08-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190804_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contect',
            new_name='Contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
