# Generated by Django 2.2.2 on 2019-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190804_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_category', models.CharField(max_length=50)),
                ('stock', models.IntegerField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
    ]
