# Generated by Django 2.2.2 on 2019-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='p_company',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
