# Generated by Django 2.2.2 on 2019-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190805_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_stock',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_category', models.CharField(max_length=50)),
                ('p_company', models.CharField(max_length=50)),
                ('p_img', models.ImageField(upload_to='upload/')),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'a_stock',
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
