# Generated by Django 2.2.2 on 2019-08-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190812_1414'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='a_stock',
            table='stocks',
        ),
    ]
