# Generated by Django 2.2.2 on 2019-08-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20190813_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='a_stock',
            new_name='Stocks',
        ),
    ]
