# Generated by Django 2.2.2 on 2019-09-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20190813_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
