# Generated by Django 2.2.2 on 2019-09-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190926_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registation',
        ),
    ]
