# Generated by Django 2.2.2 on 2019-09-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_registation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registation',
        ),
    ]
