# Generated by Django 2.2.2 on 2019-10-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_a_registation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a_login',
        ),
    ]
